export const ADD_DEVELOPER = 'ADD_DEVELOPER';
export const GET_ALL_DEVELOPERS = 'GET_ALL_DEVELOPERS';
export const GET_SINGLE_DEVELOPER = 'GET_SINGLE_DEVELOPER';
export const SET_DEVELOPERS = 'SET_DEVELOPERS';
